import type { Metadata } from "next";
import "./globals.css";
import { ModalProvider } from "@/providers/modal-provider";
import { ToastProvider } from "@/providers/toast-provider";
import store from "@/hooks/store";
import { Provider } from "react-redux";
import ReduxProvider from "@/providers/redux-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={`font-estedad`}>
        <ReduxProvider>
          <ModalProvider />
          {children}
          <ToastProvider />
        </ReduxProvider>
      </body>
    </html>
  );
}
